version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ems6db_7ylj_user:0qVBn3zvhf6OzAzApNXnyGwEh4bGk2UK@dpg-d38osi63jp1c73asruhg-a.oregon-postgres.render.com/ems6db_7ylj
      - SESSION_SECRET=super-secret-key
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=True

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ems6db_7ylj_user
      POSTGRES_PASSWORD: 0qVBn3zvhf6OzAzApNXnyGwEh4bGk2UK
      POSTGRES_DB: ems6db_7ylj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:

